### ISSUE TITLE
Exception Android on prod - Fatal Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by puzakd** [Lightstreamer/lightstreamer_flutter_client#2]
Following the recent update, we've encountered an issue with an early crash in the Android Java implementation, specifically pointing to the `LightstreamerFlutterClientPlugin`. This crash occurs during the application startup. Could you please review the provided crash log below and provide guidance on resolving this issue?

*Proguard is disabled in gradle config.

```
Fatal Exception: java.lang.NoClassDefFoundError: com.lightstreamer.client.LSLightstreamerClient$LSLightstreamerClient_randomMillis
       at com.lightstreamer.client.LSLightstreamerClient.<init>(LightstreamerClient.hx:55)
       at com.lightstreamer.client.LightstreamerClient.<init>()
       at com.lightstreamer.lightstreamer_flutter_client.LightstreamerFlutterClientPlugin.<init>(LightstreamerFlutterClientPlugin.java:47)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:79)
       at io.flutter.embedding.android.FlutterFragment.configureFlutterEngine(FlutterFragment.java:1531)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:213)
       at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:1062)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:3068)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:490)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:265)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
       at android.app.Activity.performStart(Activity.java:6456)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2508)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2605)
       at android.app.ActivityThread.access$1100(ActivityThread.java:165)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:179)
       at android.app.ActivityThread.main(ActivityThread.java:5730)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
```

**Comment by puzakd** [comment]
this issue is easy to replicate if run the app on Android 6
crash log point me out to this line 
![image](https://github.com/Lightstreamer/lightstreamer_flutter_client/assets/115468416/392ce95a-9f04-4cf3-ac43-02305502ce9e)

**Comment by Bravo27** [comment]
At the moment the minimum requirements of the Lightstreamer Flutter Plugin for Android platform is Android api level 26.

**Comment by dkaera** [comment]
thanks @Bravo27 
Could you please add a reference indicating that the LS plugin supports a minimum SDK level of 26? This is important to clarify because even the [sample](https://github.com/Lightstreamer/lightstreamer_flutter_client/blob/1df3b4961bcfe904ec9f8b6a9d86d79117ab5072/example/android/app/build.gradle#L33) on GitHub specifies a minSdkVersion of 23.

**Comment by Bravo27** [comment]
Apologies for any confusion caused by the current documentation. We're aware of the issue and will be updating the minimum API level requirement shortly.

**Comment by Bravo27** [comment]
API level requirements updated in the project.
